# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 22:46
from __future__ import unicode_literals

import bookstore.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='book',
            field=models.FileField(upload_to=b'', validators=[bookstore.validate.validate_file_extension]),
        ),
    ]
