# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20160728_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='book_cover',
            field=models.ImageField(upload_to=b''),
        ),
    ]
