# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20160730_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='book_cover',
        ),
        migrations.AddField(
            model_name='addbook',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='addbook',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='addbook',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
    ]
