# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20160801_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='addbook',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='addbook',
            name='book_cover',
            field=models.ImageField(default=datetime.datetime(2016, 8, 4, 17, 14, 28, 454470, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
